# Generated by Django 6.1 on 2026-09-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_path', models.CharField(default='/wdc/papermc', max_length=255)),
                ('rcon_port', models.IntegerField(default=25575)),
                ('rcon_password', models.CharField(blank=True, max_length=128)),
                ('max_ram_mb', models.IntegerField(default=4096, help_text='Allocated RAM in MB')),
            ],
        ),
    ]
