# Generated by Django 6.1 on 2026-09-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversetting',
            name='server_path',
            field=models.CharField(default='/wdc/PaperMC', max_length=255),
        ),
    ]
