# Generated by Django 6.1 on 2026-08-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('ts', models.BigIntegerField()),
                ('answered', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['ts'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('votes', models.JSONField(default=list)),
                ('active', models.IntegerField(default=0)),
                ('type', models.CharField(default='standard', max_length=50)),
                ('scope', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'polls',
            },
        ),
    ]
