# Generated by Django 6.1 on 2026-08-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scquizz', '0002_quizsession_message_session_poll_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='cooldown_seconds',
            field=models.PositiveIntegerField(default=60, help_text='เวลารอระหว่างข้อความ (วินาที) ที่แสดงใน UI'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='rate_limit_per_minute',
            field=models.PositiveIntegerField(default=10, help_text='จำนวนข้อความสูงสุดต่อ IP ต่อนาที (0 = ไม่จำกัด)'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
