# Generated by Django 6.1 on 2026-09-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scquizz', '0003_quizsession_cooldown_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='cooldown_seconds',
            field=models.PositiveIntegerField(default=0, help_text='เวลารอระหว่างข้อความ (วินาที) (0 = ไม่จำกัด)'),
        ),
    ]
