# Generated by Django 6.1 on 2026-08-28 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('app_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='🚀', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='True if accessible without login')),
                ('min_role_required', models.CharField(choices=[('viewer', 'Viewer (เข้าชมได้)'), ('moderator', 'Moderator (จัดการข้อมูล)'), ('admin', 'Admin (ผู้ดูแลแอปเต็มรูปแบบ)')], default='viewer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
                'db_table': 'core_app_settings',
            },
        ),
        migrations.CreateModel(
            name='GroupAppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('none', 'No Access (ไม่มีสิทธิ์)'), ('viewer', 'Viewer (ดูข้อมูล/เล่นแอป)'), ('moderator', 'Moderator (จัดการข้อมูลในแอป)'), ('admin', 'Admin (ผู้ดูแลแอป)')], default='viewer', max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='auth.group')),
            ],
            options={
                'db_table': 'core_group_app_permissions',
                'unique_together': {('group', 'app_name')},
            },
        ),
        migrations.CreateModel(
            name='UserAppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('none', 'No Access (ไม่มีสิทธิ์)'), ('viewer', 'Viewer (ดูข้อมูล/เล่นแอป)'), ('moderator', 'Moderator (จัดการข้อมูลในแอป)'), ('admin', 'Admin (ผู้ดูแลแอป)')], default='viewer', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_user_app_permissions',
                'unique_together': {('user', 'app_name')},
            },
        ),
    ]
