# Generated by Django 6.1 on 2026-08-28 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(max_length=150)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('success', 'เข้าสู่ระบบสำเร็จ'), ('failed', 'เข้าสู่ระบบไม่สำเร็จ')], default='success', max_length=20)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Login Log',
                'verbose_name_plural': 'User Login Logs',
                'db_table': 'core_user_login_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
