# Generated by Django 6.1 on 2026-09-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userloginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='icon',
            field=models.CharField(default='🚀', max_length=255),
        ),
    ]
