# Generated by Django 6.1 on 2026-08-27 19:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMarker',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อสถานที่ / จุดปักหมุด')),
                ('category', models.CharField(default='ทั่วไป', max_length=100, verbose_name='หมวดหมู่')),
                ('description', models.TextField(blank=True, default='', verbose_name='รายละเอียด')),
                ('latitude', models.FloatField(verbose_name='ละติจูด (Latitude)')),
                ('longitude', models.FloatField(verbose_name='ลองจิจูด (Longitude)')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='ที่อยู่ / บริเวณใกล้เคียง')),
                ('created_by', models.CharField(default='ผู้ใช้ทั่วไป', max_length=150, verbose_name='ผู้บันทึก')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่บันทึก')),
            ],
            options={
                'verbose_name': 'Location Marker',
                'verbose_name_plural': 'Location Markers',
                'db_table': 'location_markers',
                'ordering': ['-created_at'],
            },
        ),
    ]
